### ISSUE TITLE
can't find the main.py

### ISSUE THREAD

**Issue by Tianxu-Jia** [otonomee/streamstem#1]
Sorry, I can't find the main.py

**Comment by otonomee** [comment]
Hi @Tianxu-Jia , I somehow let your message escape through the cracks all these months and I am so sorry for not getting back until now. 

The proper script is `application.py` - you were correct to try `main.py`, since thats what the readme said (which was an oversight error and have since corrected). 

Thank you for bringing that to my attention. I'm going to close this but please [feel free to reach out](mailto:otonomee@gmail.com) with any additional concerns or questions.
